### PR TITLE
Send pigeon version with keepalive message

### PR DESCRIPTION
**Pull request by ToasterTheBrave**
# Related Github tickets

- https://github.com/VolumeFi/paloma/issues/462

# Background

We want to start enforcing a minimum version of Pigeon running against Paloma.  To do this, Pigeon needs to send its current version along with the keepalive messages.

There is also a bit of unrelated test updates to clean up nearby tests

# Testing completed

- [x] test coverage exists or has been added/updated
- [x] tested in a private testnet

# Breaking changes

- [x] I have checked my code for breaking changes

### CODE REVIEW

**Review by byte-bandit — APPROVED** [review]
Nice!

In a more broad context, I think it would make sense to combine the sources of Paloma and Pigeon in a mono repo. Not only would it make code sharing more straight forward, it will also allow for a more tight version coupling, as one starts to think of both services as a unit that's released under one identical version, therefore snapshotting the combination.

**Comment by ToasterTheBrave** [comment]
@byte-bandit That definitely warrants some further discussion.  Most chains separate these two, likely because not all nodes need to run a Pigeon.  Only validators do.  We should definitely weight the pros and cons of merging the two.

**Comment by taariq** [comment]
But to the question of monorepo, I think most OTHER cross-chain cosmos chains keep their relayer and cosmos-sdk in the same repo. I think only Sommelier split it out because it's relayer/orchestrator was written in Rust.

**Comment by byte-bandit** [comment]
@ToasterTheBrave @taariq 
Just to be clear, organising Code in a mono repo does not mean ending up with one binary. Deployment wise, nothing would have to change. But both binaries are easily tracked down to one shared git version/commit hash if needed. You start to think of a distributed system more like a global snapshot as opposed to individual fully autonomous units. 

But yeah, it's a bigger discussion. We can move it to Notion.

**Pull request merged**
