### PR TITLE
Better logic for checking for executed messages

### PR DESCRIPTION
**Pull request by ToasterTheBrave**
# Related Github tickets

- https://github.com/VolumeFi/paloma/issues/782

# Background

I'm not actually sure how this hasn't been broken for a much longer time.  When checking if a logic call was already executed, the filter topic is returning other logic calls with different IDs.  The current check of "are they any?" isn't sufficient.

Now, we are going through the returned logs and comparing the message ID of the log to the current message ID
# Testing completed

- [x] test coverage exists or has been added/updated
- [x] tested in a private testnet

# Breaking changes

- [x] I have checked my code for breaking changes

### CODE REVIEW

**Comment by ToasterTheBrave** [comment]
@byte-bandit This now has tests and has been tested in a local private testnet.  Ready for review/merging.

**Review by byte-bandit — APPROVED** [review]
🚀

**Comment by byte-bandit** [comment]
@ToasterTheBrave Good stuff. It should definitely reduce the amount of noise we get from this obscure behaviour. 

How are you feeling about adding this and your recent change to Pigeon to the `1.8.2` release before that goes live tomorrow?

**Comment by ToasterTheBrave** [comment]
@byte-bandit Sorry, I missed your message.  Glad to see you put it into the release :+1:

**Pull request merged**
